# Configuration file for training and evaluation

# Reproducibility
seed: 42

dataset:
  # Options: IP102, Cotton80, SoyLocal
  name: IP102
  root: ./data/IP102
  batch_size: 32
  num_workers: 6

model: # Timm model names
  # name: resnetrs200
  # name: vgg19_bn
  # name: resnet50
  name: tiny_vit_21m_384
  pretrained: true

other:
  edg:
    aug_net: true
    grad_feature: true

training:
  epochs: 20
  learning_rate: 0.001
  weight_decay: 0.0001
  device: cuda

logging:
  save_dir: ./logs